### ISSUE TITLE
Bundling fails when html file is missing for vulcanization

### ISSUE THREAD

**Issue by tpluscode** [Hypercubed/systemjs-plugin-html#10]
Hi. There's a small issue that bundling will fail when the output html file for running vulcanize is not  present. It's as simple as `touch build.html` for the bundle command to succeed

**Comment by Hypercubed** [comment]
Under what circumstance is this plugin trying to vulcanize a missing file?  If there are no `!html` imports then there should be no `build.html` and therefore no attempt to vulcanize.  Do you have a setup I can look at?

**Comment by tpluscode** [comment]
Sure, you can bundle [tpluscode/md-ed](/tpluscode/md-ed). Just delete the dist folder and run `npm run bundle-bower` or `npm run build-jspm`. The former does `bundle-sfx` and the latter is `jspm bundle`

**Comment by tpluscode** [comment]
And, sorry if I wasn't clear. The plugin is not trying to bundle a missing file. 

It fails when the output HTML file does not exist before bundling

**Comment by Hypercubed** [comment]
It looks to me that the problem is systemjs-plugin-html is trying to write the html file before the SystemJS build has had a chance to create the output directory.  I'm not sure why this is.

For now, the best solution on your end is to add `mkdir -p dist/jspm` to your build step while I investigate further.  Let me know if this works.

**Comment by tpluscode** [comment]
The latest code fixes this issue. Thanks. Please let me know when you release it
